### PR TITLE
fix explicit cast error on newer mac versions

### PR DESCRIPTION
**Pull request by dseif0x**

### CODE REVIEW

**Comment by Emoun** [comment]
Hi, what does this fix due and why is it useful? Does it fix (on its own) the issue with macs building?

**Comment by R3freshReload** [comment]
Yes exactly. It fixes one of the 2 issues that cause the mac builds to fail. The other issue is that for some reason makeinfo is not available on newer mac version but that is simply fixed by adding it to the github actions file that installa the build dependencies using brew.

**Comment by R3freshReload** [comment]
For my [fork of the patmos-llvm-project](https://github.com/R3freshReload/patmos-llvm-project) I have changed the dependency for newlib to the one I am trying to merge here to verify that it works and the build passes on all macos versions now.

**Comment by Emoun** [comment]
Yes, very good! I'll merge this. Can I ask you to make PR to patmos-llvm-project's master branch that adds your CI fixes too? Extract it from the rest of your work, which we will do an independent PR for

**Pull request merged**
